name: fluttermvvmtemplate
description: A Flutter template project for everyone.

publish_to: none 

version: 0.0.9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^6.0.4
  

  # network
  # dio: ^4.0.0-prev3
  vexana: ^3.0.1

  # database
  shared_preferences: ^2.0.5

  # language
  easy_localization: ^3.0.0

  # firebase
  firebase_core: ^2.1.1
  firebase_analytics: any
  
  # core utilities
  kartal: ^2.1.0
  logger: ^1.0.0
  webview_flutter: ^4.0.6
  equatable: ^2.0.5

  # ui utilities
  animations: ^2.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0-nullsafety
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^2.0.3
  lottie: ^2.2.0
  shimmer: ^2.0.0-nullsafety.0

  architecture_theme:
    git:  https://github.com/VB10/architecture_theme.git
  architecture_widgets:
    path: module/architecture_widgets
  all_of_template:
    path: module/all_of_template

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  json_annotation: ^4.0.1
  json_serializable: ^6.5.4
  mobx_codegen: ^2.0.1+3
  mockito: any
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - asset/lang/
    - asset/svg/
    - asset/image/
    - asset/lottie/